# NOTE: Generated By HttpRunner v4.3.0
# FROM: .\testsuites\test_suite.yml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from testcases.get_token_case_test import TestCaseGetTokenCase as GetTokenCase
from testcases.select_token_case_test import TestCaseSelectTokenCase as SelectTokenCase


class TestCaseTestSuite(HttpRunner):

    config = Config("testcase description")

    teststeps = [
        Step(RunTestCase("/cgi-bin/token").call(GetTokenCase)),
        Step(RunTestCase("/cgi-bin/select_token").call(SelectTokenCase)),
    ]


if __name__ == "__main__":
    TestCaseTestSuite().test_start()
