# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcases\get_token_case.yml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from api.get_token_test import TestCaseGetToken as GetToken


class TestCaseGetTokenCase(HttpRunner):

    config = Config("testcase description")

    teststeps = [
        Step(RunTestCase("/cgi-bin/token").call(GetToken)),
    ]


if __name__ == "__main__":
    TestCaseGetTokenCase().test_start()
