# NOTE: Generated By HttpRunner v4.3.0
# FROM: edit_token_case.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseEditToken(HttpRunner):

    config = Config("testcase description").variables(
        **{
            "appid": "wxe6d35c5fb83d7039",
            "grant_type": "client_credential",
            "secret": "648f2af46d5cfd59fc0feb2b6c4019e0",
        }
    )

    teststeps = [
        Step(
            RunRequest("/cgi-bin/token")
            .get("https://api.weixin.qq.com/cgi-bin/token")
            .with_params(
                **{"appid": "$appid", "grant_type": "$grant_type", "secret": "$secret"}
            )
            .with_headers(
                **{
                    "Authorization": "Basic MTox",
                    "Postman-Token": "ffca98ac-6e08-4d2b-ba79-cef085465e45",
                    "User-Agent": "PostmanRuntime/7.32.2",
                }
            )
            .extract()
            .with_jmespath("body.access_token", "access_token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; encoding=utf-8")
        ),
        Step(
            RunRequest("/cgi-bin/tags/update")
            .post("https://api.weixin.qq.com/cgi-bin/tags/update")
            .with_params(**{"access_token": "$access_token"})
            .with_headers(
                **{
                    "Content-Type": "application/json",
                    "Postman-Token": "4228ca32-e415-4007-87de-98e7b117aced",
                    "User-Agent": "PostmanRuntime/7.32.2",
                }
            )
            .with_json(
                {"tag": {"id": 162, "name": "木子${get_random_number(100000,999999)}"}}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; encoding=utf-8")
            .assert_equal("body.errcode", 0)
            .assert_equal("body.errmsg", "ok")
        ),
    ]


if __name__ == "__main__":
    TestCaseEditToken().test_start()
