# NOTE: Generated By HttpRunner v4.3.0
# FROM: api\get_token.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseGetToken(HttpRunner):

    config = Config("testcase description").variables(
        **{
            "appid": "wxe6d35c5fb83d7039",
            "grant_type": "client_credential",
            "secret": "648f2af46d5cfd59fc0feb2b6c4019e0",
        }
    )

    teststeps = [
        Step(
            RunRequest("/cgi-bin/token")
            .get("https://api.weixin.qq.com/cgi-bin/token")
            .with_params(
                **{"appid": "$appid", "grant_type": "$grant_type", "secret": "$secret"}
            )
            .with_headers(
                **{
                    "Authorization": "Basic MTox",
                    "Postman-Token": "b4b7b7a2-e6fd-46b7-976f-dbfe4f8a8664",
                    "User-Agent": "PostmanRuntime/7.32.2",
                }
            )
            .extract()
            .with_jmespath("body.access_token", "access_token")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseGetToken().test_start()
