# NOTE: Generated By HttpRunner v4.3.0
# FROM: api\select_token.yml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseSelectToken(HttpRunner):

    config = Config("testcase description").variables(
        **{"access_token": "$access_token"}
    )

    teststeps = [
        Step(
            RunRequest("/cgi-bin/tags/get")
            .get("https://api.weixin.qq.com/cgi-bin/tags/get")
            .with_params(**{"access_token": "$access_token"})
            .with_headers(
                **{
                    "Postman-Token": "c83ad029-b706-4166-8707-2b98be52346b",
                    "User-Agent": "PostmanRuntime/7.32.2",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; encoding=utf-8")
        ),
    ]


if __name__ == "__main__":
    TestCaseSelectToken().test_start()
